### ISSUE TITLE
Add selectable persona detail component

### ISSUE THREAD

**Issue by Feichtmeier** [hs-duesseldorf/klimabox-story#4]
![](
https://user-images.githubusercontent.com/15329494/106457015-9e5d9980-648e-11eb-8c50-0bfd8e717e0b.png)

**Comment by marcelmuecke** [comment]
### Finales Layout
<img width="860" alt="Bildschirmfoto 2021-02-06 um 23 42 35" src="https://user-images.githubusercontent.com/62099577/107131283-459a6080-68d5-11eb-9925-b1cc683306e6.png">

Anmerkungen:
* Funktioniert wie Akkordionartikel, die Inhalte klappen unter dem zugehörigen Teaser-Banner mit Name und Artikelname aus.
* Später wäre es gut, wenn nur ein Artikel auf einmal geöffnet sein kann. Wenn ich einen anderen öffne, schließt sich der, der aktuell geöffnet ist.
* Als Wunsch von Patrick und Tina wäre langfristig gut, dass das Herausfahren/klappen/… der Inhalte aus dem Teaser-Banner animiert ist. Zu Beginn sollten alle Artikel geschlossen sein. Wenn man auf die Komponente scrollt, sollte der erste Artikel herausklappen um Usern anzudeuten, dass hier interagiert werden kann.

**Comment by marcelmuecke** [comment]
Xd-Entwicklerlink wurde auch mit dem Layout aktualisiert: https://xd.adobe.com/view/74f701c0-d072-427b-8be0-e82020f63e6a-21a4/

**Comment by Feichtmeier** [comment]
Sehr cool, vielen Dank!

**Comment by Feichtmeier** [comment]
Moment mal, das ist doch der Audio accordion :) ich glaube wir sind im issue verrutscht

**Comment by marcelmuecke** [comment]
Oh! Weiter oben war dieses Bild kommentiert: https://user-images.githubusercontent.com/15329494/106457015-9e5d9980-648e-11eb-8c50-0bfd8e717e0b.png Daher dachte ich, es geht um diese Komponente. Das ist das neue Layout davon. Derzeit sind nur Audio-Accordions geplant, eventuelle Video- und Textinterviews wurden erstmal auf Eis gelegt

**Comment by Feichtmeier** [comment]
Alles klar dann kopiere ich deinen beitrag rüber
