### ISSUE TITLE
adjust header component

### ISSUE THREAD

**Issue by alot210** [hs-duesseldorf/klimabox-story#57]
### Header component

- add klimabox logo
- add link **_about_** to nav; change order of nav links; rename blog to **_archive_**
- add search icon (no functionality necessary at the moment)
- add login and register button (no functionality necessary at the moment)

<img width="720" alt="Bildschirmfoto 2021-05-07 um 13 30 07" src="https://user-images.githubusercontent.com/19333585/117443516-876c8e80-af38-11eb-8fba-70cc373aef61.png">

**Comment by paulkre** [comment]
Ist das Logo eigentlich noch aktuell? Patrick meinte letztens, dass gerade ein neues entwickelt wird.

**Comment by alot210** [comment]
@paulkre 

> Ist das Logo eigentlich noch aktuell? Patrick meinte letztens, dass gerade ein neues entwickelt wird.

Bin ich mir nicht sicher. Merke mir die Frage für nächste Woche. Ein Logo für den weißen Hintergrund fehlt so wie ich das sehe auch noch.
