### ISSUE TITLE
add chapter overview in chapter-1

### ISSUE THREAD

**Issue by alot210** [hs-duesseldorf/klimabox-story#59]
### Chapter overview with links to other chapters

- add header _**Kapitelübersicht**_
- add tiles with links to each chapter
- add button _**starten**_

<img width="707" alt="Bildschirmfoto 2021-05-07 um 13 44 58" src="https://user-images.githubusercontent.com/19333585/117444999-79b80880-af3a-11eb-8447-40331fce659c.png">

**Comment by alot210** [comment]
@KomanechiL Das ist auch schon done, oder?

**Comment by KomanechiL** [comment]
@alot210 ja soweit ich das gesehen habe, wurde es von Paul schon umgesetzt

**Comment by paulkre** [comment]
Sorry, ich halte mich ab jetzt an die Github Regeln. Wollte nur so schnell wie möglich einen repräsentablen Stand aufsetzen.

**Comment by paulkre** [comment]
Closed in 9c6690e1843392d662b703cb79c574e284daef7a.
