### ISSUE TITLE
add arctic and city screen chapter-1

### ISSUE THREAD

**Issue by alot210** [hs-duesseldorf/klimabox-story#61]
### Chapter 1 arctic and city scene UI

- first scene with parallax scrolling animation

<img width="365" alt="Bildschirmfoto 2021-05-07 um 13 57 09" src="https://user-images.githubusercontent.com/19333585/117446380-4b3b2d00-af3c-11eb-8be7-378e2fe7bab4.png">
<img width="365" alt="Bildschirmfoto 2021-05-07 um 13 57 20" src="https://user-images.githubusercontent.com/19333585/117446387-4d04f080-af3c-11eb-96b6-242cd962b464.png">
<img width="360" alt="Bildschirmfoto 2021-05-07 um 13 57 28" src="https://user-images.githubusercontent.com/19333585/117446391-4d9d8700-af3c-11eb-8e71-7178e3abd5d1.png">
<img width="364" alt="Bildschirmfoto 2021-05-07 um 13 57 36" src="https://user-images.githubusercontent.com/19333585/117446398-4f674a80-af3c-11eb-9a6d-59c68c054410.png">
<img width="363" alt="Bildschirmfoto 2021-05-07 um 13 57 45" src="https://user-images.githubusercontent.com/19333585/117446400-50987780-af3c-11eb-8537-7df522182b14.png">
<img width="364" alt="Bildschirmfoto 2021-05-07 um 13 57 51" src="https://user-images.githubusercontent.com/19333585/117446403-51310e00-af3c-11eb-9f94-65f30d2b5eb7.png">

**Comment by alot210** [comment]
@paulkre Hey hab gesehen, dass das auch schon umgesetzt ist, aber irgendwie nicht ganz bzw. anders als in den Screens. Stimmt das so? Soll nach dem Sonnenuntergang dann der Zoom ins Fenster kommen?

**Comment by paulkre** [comment]
Jep, ist auf jeden Fall noch WIP. Lass uns das beim nächsten Meeting besprechen.
