### ISSUE TITLE
Chapter-2 Overview

### ISSUE THREAD

**Issue by KomanechiL** [hs-duesseldorf/klimabox-story#66]
![image](https://user-images.githubusercontent.com/32469496/118397383-f55d3800-b653-11eb-9e48-48af481c0cb6.png)

TODO:
-Background Image 
-Add Text

**Comment by alot210** [comment]
"Kapitel 2" und "Zum starten runterscrollen" könnte noch mehr padding haben.

<img width="1646" alt="Bildschirmfoto 2021-05-16 um 16 58 30" src="https://user-images.githubusercontent.com/19333585/118401967-09ab3000-b668-11eb-9201-fc5a3d9543d8.png">

Die Pfeile könnten zudem animiert werden wie auch auf der Startseite.
